// Content baseline: main at 6630d80569504064bb21b0e5d4d3eeada4f922b6.
// Entry order, wording, dates, and repetitions follow resume.tex.
// Absent `active` means true. Archived content is explicitly inactive.
// Keep presentation settings in resume.typ; content may use semantic emphasis.
#let cv = (
  profile: (
    name: "Prateek Dwivedi",
    alternate-name: "प्रतीक द्विवेदी",
    address: "4B09, IT University of Copenhagen",
    email: "prdw@itu.dk",
    website: (label: "prateekdwivedi.in", url: "https://www.prateekdwivedi.in/"),
  ),
  sections: (
    (
      title: "Research Interests",
      kind: "prose",
      entries: ((description: [My research focuses on the theoretical foundations of computer science, with particular emphasis on *Algebraic Complexity Theory* and *Computational Complexity*.]),),
    ),
    (
      title: "Employment",
      kind: "appointment",
      entries: ((
        institution: "IT University of Copenhagen",
        location: "Copenhagen, Denmark",
        role: "Postdoctoral Researcher",
        dates: "2024 -",
        department: "Theoretical Computer Science Section",
        adviser: (label: "Adviser:", name: "Prof Nutan Limaye", url: "https://www.itu.dk/~nuli/"),
      ),),
    ),
    (
      title: "Education",
      kind: "appointment",
      entries: (
        (
          institution: "Indian Institute of Technology Kanpur",
          location: "Kanpur, India",
          role: "Doctor of Philosophy",
          dates: "2018 - 2025",
          department: "Computer Science and Engineering",
          thesis: (
            label: "Thesis:",
            title: "Treading the Borders for Explicitness, Circuit Factoring, and Identity Testing",
            link-label: "pdf",
            url: "https://www.prateekdwivedi.in/papers/thesis.pdf",
          ),
          adviser: (label: "Adviser:", name: "Prof Nitin Saxena", url: "https://cse.iitk.ac.in/users/nitin/"),
        ),
        (
          institution: "KCC Institute of Technology and Management",
          location: "Gautam Buddha Nagar, India",
          role: "Bachelor of Technology",
          dates: "2013 - 2017",
          department: "Computer Science and Engineering",
        ),
      ),
    ),
    (
      title: "Publications",
      kind: "publication",
      entries: (
        (
          title: "Lower Bounds in Algebraic Complexity via Symmetry and Homomorphism Polynomials",
          dates: "2025",
          authors: "with Benedikt Pago and Tim Seppelt",
          venue: "Submitted, 2025",
        ),
        (
          title: "On Closure Properties of Read-Once Oblivious Algebraic Branching Programs",
          url: "https://arxiv.org/abs/2509.10725",
          dates: "2025",
          authors: "with Robert Andrews, Jules Armand, Magnus Hansen, Nutan Limaye, Srikanth Srinivasan, and Sébastien Tavenas",
          venue: "17th Innovations in Theoretical Computer Science (ITCS), 2026",
        ),
        (
          title: "A primer on the closure of algebraic complexity classes under factoring",
          url: "https://arxiv.org/abs/2506.19604",
          dates: "2025",
          authors: "with C. S. Bhargav and Nitin Saxena",
          venue: "To appear in the proceedings of Recent Trends in Computer Algebra (RTCA), 2025",
        ),
        (
          title: "Monotone bounded-depth complexity of homomorphism polynomials",
          url: "https://arxiv.org/abs/2505.22894",
          dates: "2024",
          authors: "with C. S. Bhargav, Shiteng Chen, Radu Curticapean",
          venue: "50th International Symposium on Mathematical Foundations of Computer Science (MFCS), 2025",
        ),
        (
          title: "Learning the coefficients: A presentable version of border complexity and applications to circuit factoring",
          url: "https://www.prateekdwivedi.in/papers/PresentableVNP-confversion.pdf",
          dates: "2024",
          authors: "with C. S. Bhargav and Nitin Saxena",
          venue: "56th Annual ACM Symposium on Theory of Computing (STOC), 2024",
        ),
        (
          title: "Lower bounds for the sum of small-size algebraic branching programs",
          url: "https://www.prateekdwivedi.in/papers/smABP-lowerbounds-confversion.pdf",
          dates: "2024",
          authors: "with C. S. Bhargav and Nitin Saxena",
          venue: "19th Annual Conference of Theory and Applications of Models of Computation (TAMC), 2024",
          note: "Invited in the special issue of Theoretical Computer Science (Theor. Comput. Sci.)",
        ),
        (
          title: "Demystifying the border of depth-3 algebraic circuits",
          url: "https://www.prateekdwivedi.in/papers/border-depth3-fullversion.pdf",
          dates: "2021",
          authors: "with Pranjal Dutta and Nitin Saxena",
          venue: "62nd Annual Symposium on Foundations of Computer Science (FOCS)",
          note: "Invited in the special issue of SIAM Journal on Computing (SICOMP)",
        ),
        (
          title: "Deterministic identity testing paradigms for bounded top-fanin depth-4 circuits",
          url: "https://www.prateekdwivedi.in/papers/pit-depth4-didi-fullversion.pdf",
          dates: "2021",
          authors: "with Pranjal Dutta and Nitin Saxena",
          venue: "36th Computational Complexity Conference (CCC)",
          note: "The full version is currently under review in Theory of Computing (ToC)",
        ),
      ),
    ),
    (
      title: "Academic Talks and Seminars",
      kind: "talk",
      entries: (
        (title: "Non-Closure properties in algebraic complexity", dates: "2025", venue: "IIT Delhi, India"),
        (title: "Monotone Bounded-Depth Complexity of Homomorphism Polynomials", dates: "2024", venue: "ARCO, Malmö University, Sweden"),
        (
          title: "Presentable Version of Border Complexity and Applications to Circuit Factoring",
          children: (
            (venue: "Ulm University, Germany", dates: "2024"),
            (venue: "Welcome talk at the Theory Group, ITU, and BARC, KU", dates: "2024"),
          ),
        ),
        (title: "Treading the Border Complexity and Identity Testing Paradigms", dates: "2022", venue: "Thesis Defense, IIT Kanpur"),
        (title: "Deterministic identity testing paradigms for bounded top-fanin depth 4 circuits", dates: "2021", venue: "Invited Talk, CS Theory Seminar at Georgetown University"),
        (
          title: "Deterministic identity testing paradigms for bounded top-fanin depth-4 circuits",
          children: (
            (venue: "Workshop on Algebra and Computation (WAC), Göteborg", dates: "2023"),
            (venue: "7th Workshop on Algebraic Complexity Theory (WACT), Warwick", dates: "2023"),
            (venue: "CS Theory Seminar at Georgetown University", dates: "2021"),
            (venue: "Conference Presentation, (CCC)", dates: "2021"),
          ),
        ),
        (title: "Information-Theoretic And Algorithmic Thresholds For Group Testing", dates: "2020", venue: "PhD Comprehensive Evaluation, IIT Kanpur"),
        (title: "On Approximative Closure of Algebraic Complexity Classes", dates: "2019", venue: "SIGTACS, IIT Kanpur"),
      ),
    ),
    (
      title: "Relevant Courses",
      kind: "course",
      active: false,
      entries: (
        (active: false, title: "Arithmetic Circuit Complexity"),
        (active: false, title: "Computational Number Theory & Algebra"),
        (active: false, title: "Randomized methods in Computational Complexity"),
        (active: false, title: "Design and Analysis of Algorithms"),
        (active: false, title: "Randomized Algorithms"),
        (active: false, title: "Data Structures"),
        (active: false, title: "Discrete Mathematics and Graph Theory"),
        (active: false, title: "Numerical and Statistical Techniques"),
        (active: false, title: "Theory of Computation."),
      ),
    ),
    (
      title: "Short Term Visits",
      kind: "visit",
      entries: (
        (title: "50th International Symposium on Mathematical Foundations of Computer Science (MFCS)", dates: "2025", location: "Warsaw, Poland"),
        (title: "57th Annual ACM Symposium on Theory of Computing (STOC)", dates: "2025", location: "Prague, Czech Republic"),
        (title: "Université Savoie Mont Blanc, France", dates: "2025", host: "Host: Prof. Sébastien Tavenas"),
        (title: "Tata Institute of Fundamental Research (TIFR), Mumbai", dates: "2025", host: "Host: Prof Mrinal Kumar"),
        (title: "Ulm University, Germany", dates: "2024", host: "Host: Prof Thomas Thierauf"),
        (title: "Algorithmic Research-Cooperation around Oresund (ARCO)", dates: "2024", location: "Malmö University, Sweden"),
        (title: "Summer of Counting and Algebraic Complexity", dates: "2023", location: "IT University of Copenhagen (ITU) in Copenhagen, Denmark"),
        (title: "Workshop on Algebra and Computation (WAC)", dates: "2023", location: "Chalmers University of Technology, Göteborg"),
        (title: "7th Workshop on Algebraic Complexity Theory (WACT)", dates: "2023", location: "The University of Warwick, UK"),
        (title: "2nd Swiss Winter School on Theoretical Computer Science", dates: "2023", location: "Jointly organized by EPFL and ETH Zurich in Zinal"),
        (title: "Chennai Mathematical Institute (CMI)", dates: "2022", host: "Host: Prof Partha Mukhopadhyay"),
        (title: "62nd Annual Symposium on Foundations of Computer Science (FOCS)", dates: "2022", location: "Denver, Colorado - Attended Virtually"),
        (title: "36th Computational Complexity Conference (CCC), 2021.", dates: "2021", location: "Toronto, Ontario, Canada - Attended Virtually"),
        (title: "48th International Colloquium on Automata, Languages, and Programming (ICALP)", dates: "2021", location: "Glasgow, Scotland - Attended Virtually"),
        (title: "52nd ACM Symposium on Theory of Computing (STOC)", dates: "2020", location: "Chicago, US - Attended Virtually"),
        (title: "Workshop on Algebraic Complexity Theory", dates: "2019", location: "ICTS, Bengaluru"),
      ),
    ),
    (
      title: "Academic Achievements",
      kind: "achievement",
      entries: (
        (title: "Invited to participate in Summer of Counting and Algebraic Complexity at ITU Copenhagen", dates: "2023", description: "Full financial support"),
        (title: "Selected to attend Swiss Winter School on Theoretical Computer Science", dates: "2023", description: "Partial financial support"),
        (title: "Recipient of financial support from Microsoft Research India and IARCS-ACM India", dates: "2022", description: "To attend an academic conference"),
        (title: "Ranked 23 in Joint Entrance Screening Test (JEST)", dates: "2018"),
        (title: "Ranked 1179 in Graduate Aptitude Test in Engineering (GATE) Computer Science", dates: "2017", description: "Among approximately 1,00,000 candidates"),
        (title: "Presented undergraduate project at university-level Science and Technology Conference.", dates: "2017"),
        (title: "Academic Excellence Award", dates: "2014", description: "KCC ITM, India"),
      ),
    ),
    (
      title: "Teaching and Mentoring Experience",
      kind: "teaching",
      entries: (
        (title: "Undergraduate Project, ITU Copenhagen", dates: "2025", description: "Mentoring Thøger Bro and Emil Andreas Sondum Jointly with Prof Riko Jacob"),
        (
          title: "Head Tutor at CSE, IIT Kanpur",
          description: "Responsible for practical assignments, Lab Exam, and all the course-related logistical support",
          children: ((title: "Data Structures and Algorithms", dates: "2024"),),
        ),
        (title: "Mathematics for Computer Science, IIT Kanpur", description: "Adhyayan 2023, Summer School. Jointly with C. S. Bhargav"),
        (
          title: "Tutor at CSE, IIT Kanpur",
          children: (
            (title: "Introduction to Computing", dates: "2022"),
            (title: "Data Structures and Algorithms", dates: "2019"),
          ),
        ),
        (
          title: "Teaching Assistant at CSE, IIT Kanpur",
          children: (
            (title: "Computational Complexity", dates: "2021"),
            (title: "Modern Cryptology", dates: "2021"),
            (title: "Mathematics for Computer Science", dates: "2020"),
            (title: "Data Structures and Algorithms", dates: "2018"),
            (title: "Introduction to Computing", dates: "2018"),
          ),
        ),
        (
          title: "Teaching Assistant in Massive Online Courses",
          children: (
            (title: "Introduction to Cryptography", platform: "eMasters, IIT Kanpur", dates: "2022"),
            (title: "Randomized methods in Computational Complexity", platform: "NPTEL", dates: "2021"),
            (title: "Arithmetic Circuit Complexity", platform: "NPTEL", dates: "2020"),
            (title: "Modern Algebra", platform: "NPTEL", dates: "2019"),
          ),
        ),
      ),
    ),
    (
      title: "Professional Contributions",
      kind: "contribution",
      entries: (
        (
          title: "Reviewer for Conferences",
          descriptions: (
            "STACS 2026, STOC 2025, FOCS 2025, ITCS 2025, STOC 2025, STOC 2024, FSTTCS 2024, FOCS 2023, ISSAC 2023",
            "STOC 2023, CCC 2022, ITCS 2022, SODA 2021, FOCS 2021",
          ),
        ),
        (title: "Reviewer for journals", descriptions: ("SIAM Journal on Computing",)),
        (title: "Seminar Organiser at CSE, IIT Kanpur", descriptions: ("Regularly organise talks and seminars in a department special interest group (SIGTACS)",)),
      ),
    ),
    (
      title: "Personal Details",
      kind: "detail",
      entries: (
        (label: "Name", value: "Prateek Dwivedi (प्रतीक द्विवेदी)"),
        (label: "Gender and Pronouns", value: "Male and He/Him."),
        (label: "Permanent Address", value: "A106, Bulland Heights, Crossings Republik Ghaziabad (U.P) - 201016, India"),
        (label: "Date and place of birth", value: [21#super[st] Feb 1996, Lucknow, India]),
        (label: "Nationality", value: "Indian (भारतीय)"),
        (label: "Contact", value: "+91 8800 291 032 | +45 31 81 36 18"),
      ),
    ),
    (
      title: "Projects",
      kind: "project",
      active: false,
      entries: (
        (
          active: false,
          category: "Course Project:",
          title: "Rediscovering Randomized Median Finding Algorithm",
          institution: "IIT Kanpur",
          adviser: "Prof. Surender Baswana",
          dates: "Sept 2018–Nov 2018",
          description: "In this project we tried to re-design median finding algorithm with the optimal number of comparisons on expectation using elementary probability tools and techniques. Fundamental observations about the problem were made that gave a suitable choice of parameters which lead us to the expected result. The results from the implementation of the resulting algorithm turn out to be very close to the results in the original paper.",
        ),
        (
          active: false,
          category: "Undergraduate Project:",
          title: "Program Execution Tracer",
          institution: "KCC ITM",
          adviser: "Prof. Mandeep Kaur",
          dates: "Sept 2016–May 2017",
          description: "The aims was to present a system for facilitating novice programmers with an illustrative program execution tracer. Such a system, when provided with a syntactically and semantically correct function, aims to record the execution of each line. The recorded data can then be used to create a dynamic execution controller, with source code on one side and the state of intermediate result and output on the other side.",
        ),
        (
          active: false,
          category: "3rd year individual project:",
          title: "Blood Pressure logging and curating application",
          institution: "KCC ITM",
          adviser: "Prof. Divyanshu Sinha",
          dates: "Jun 2015",
          description: "The goal of this project was to design a mobile application which helps its user in keeping track of their Blood Pressure and provide them with a succinct report of its trends on various time frames. These reports could be shared via different messaging clients. The application would alert emergency contacts when it notices the numbers crossings the safe range.",
        ),
      ),
    ),
    (
      title: "Technical Strengths",
      kind: "detail",
      active: false,
      entries: (
        (active: false, label: "Computer Languages", value: "& C/C++, Python, Bash"),
        (active: false, label: "Software & Tools", value: "& LaTeX, GIT, Octave"),
      ),
    ),
    (
      title: "References",
      kind: "reference",
      entries: (
        (name: "Nitin Saxena", url: "https://cse.iitk.ac.in/users/nitin/", role: "Professor", institution: "IIT Kanpur", email: "nitin@cse.iitk.ac.in"),
        (name: "Nutan Limaye", url: "https://www.itu.dk/~nuli/", role: "Professor", institution: "ITU Copenhagen", email: "nuli@itu.dk"),
        (name: "Nikhil Balaji", url: "https://sites.google.com/view/nikhilbalaji/home", role: "Assistant Professor", institution: "IIT Delhi", email: "nbalaji@cse.iitd.ac.in"),
        (active: false, name: "Amit Kumar Sinhababu", url: "https://www.cmi.ac.in/people/fac-profile.php?id=amitks", role: "Assistant Professor", institution: "CMI, Chennai", email: "amitks@cmi.ac.in"),
      ),
    ),
  ),
)
